# version 0.0.2

# Run before each script
before_script:
#  - docker info
#  - echo ~/
#  - ls -all ~/.ssh
#  - git submodule init

# Update project submodules
  - git submodule update --init

types:
  - build
#  - deploy

#build_image:
#  type: build
#  script:
#    - docker build -t ubuntu:14:04
#    - docker run ubuntu:14:04 apt-get install git

# Image host voulume definition:
# /path/to/bind/from/host:/path/to/bind/in/container:rw
    
# Build    
job_ubuntu:
  type: build
  image: gitlab.ksproject.org:5000/ci/ubuntu_teonet
  #volumes (defined in /etc/gitlab-runner/config.toml): /home/kirill/_repo_:/builds/ksnet/repo:rw
  tags:
    - docker_image_run
  script:
    - cd libtrudp
    # Install dependences   
    - ci-build-data/build-ubuntu.sh
    # Make  
    - ./autogen.sh --prefix=/usr
    - make
    #- src/teoroom -?
    # Test
    #- make test
    # Build DEB package and upload it to repository
    - ci-build/make_package deb
  only:
    - tags  
    
#job_centos:
#  type: build
#  image: gitlab.ksproject.org:5000/ci/centos_teonet
#  tags:
#    - docker_image_run
#  script:
#    # Install dependences   
#    - sh/build-centos.sh
#    # Make
#    - ./autogen.sh
#    - make
#    - src/teoroom -?
#    # Test
#    #- make test
#    # Build RPM package and upload it to repository
#    - sh/make_package yum
#  only:
#    - tags  
#
#job_fedora:
#  type: build
#  image: gitlab.ksproject.org:5000/ci/fedora_teonet
#  tags:
#    - docker_image_run
#  script:
#    # Install dependences   
#    - sh/build-centos.sh
#    # Make
#    - ./autogen.sh
#    - make
#    - src/teoroom -?
#    # Test
#    #- make test
#  only:
#    - tags  
#    
#job_opensuse:
#  type: build
#  image: gitlab.ksproject.org:5000/ci/opensuse_teonet
#  tags:
#    - docker_image_run
#  script:
#    # Install dependences   
#    - sh/build-opensuse.sh
#    # Make
#    - ./autogen.sh
#    - make
#    - src/teoroom -?
#    # Test
#    #- make test
#    # Build RPM package and upload it to repository
#    - sh/make_package zyp
#  only:
#    - tags  

# Build teonet docker image and upload it to Docker HUB
#build_teonet_image:
#  type: deploy
#  tags:
#      - docker_image_build
#  script:
#    - cd ci-build-data  
#    - docker build --no-cache .
#    #- docker build -t kscherba/teonet .
#    #- docker login --username=kscherba --password=$CI_TEONET_DOCKER_PWD --email=kirill@scherba.ru
#    #- docker push kscherba/teonet
#    - docker build -t gitlab.ksproject.org:5000/teonet/teoroom:$CI_BUILD_TAG .
#    - docker push gitlab.ksproject.org:5000/teonet/teoroom:$CI_BUILD_TAG
#    # update latest
#    - docker tag -f gitlab.ksproject.org:5000/teonet/teoroom:$CI_BUILD_TAG gitlab.ksproject.org:5000/teonet/teoroom:latest
#    - docker push gitlab.ksproject.org:5000/teonet/teoroom:latest
#  only:
#    - tags  

